name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
    - run: npm --version
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/checkout@v2
      with:
        repository: keflavich/blog-theme
        path: './mine'
    - run:
        pip install -r requirements.txt
    - run:
        ls -lhd mine
    - run:
        pip install pelican
    - run:
        pelican-themes --verbose --install mine
    - run:
        pelican-themes --list
    - uses: keflavich/gh-pages-pelican-action@keflavich-v1
      with:
        PELICAN_THEME_FOLDER: mine

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_THEME_FOLDER: mine
