name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      - uses: actions/checkout@v2
        with:
          repository: keflavich/blog-theme
          path: './mine'
    - uses: keflavich/gh-pages-pelican-action@0.1.10
      with:
        PELICAN_THEME_FOLDER: mine

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_THEME_FOLDER: mine
